from __future__ import annotations

import base64
import hashlib
import importlib
import json
import re
import shutil
import subprocess
import sys
import threading
import time
from collections.abc import Callable
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Any, TypeAlias


def _optional_module(name: str) -> Any:
    try:
        return importlib.import_module(name)
    except ModuleNotFoundError:
        return None


tomllib: Any = _optional_module("tomllib") or _optional_module("tomli")
yaml: Any = _optional_module("yaml")

ROOT = Path(__file__).resolve().parent
PYTHON_TARGETS = ["danyapi", "tests", "docs", "app.py", "collecter.py", "tests.py"]
ROOT_SCRIPTS = ["app.py", "collecter.py", "tests.py"]
BANDIT_SKIPS = "B101,B104,B112,B311"
ROOT_BANDIT_SKIPS = BANDIT_SKIPS + ",B404,B603,B103"
PYLINT_DISABLES = "import-error,unsubscriptable-object,not-an-iterable"
C_SOURCES = ["danyapi/deepseek/pow_solver.c"]
CLANG_TIDY_CHECKS = (
    "clang-diagnostic-*,clang-analyzer-*,-clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling,-clang-analyzer-optin.taint.TaintedAlloc"
)

BANNED_PATTERNS = ["\u2014", "\u2013", "Zero keys.", "Ноль ключей.", "live demo"]
BANNED_SUBSTRINGS = [("generated by", "anti-ai trace"), ("co-authored-by", "anti-ai trace")]
EMOJI_RE = re.compile(
    "[\U0001f000-\U0001faff\U0001f1e6-\U0001f1ff\u231a-\u231b\u23e9-\u23f3\u25fd-\u25fe"
    "\u2614-\u2615\u2648-\u2653\u267f\u2693\u26a0-\u26a1\u26aa-\u26ab\u26bd-\u26be\u26c4-\u26c5"
    "\u26ce\u26d4\u26ea\u26f2-\u26f3\u26f5\u26fa\u26fd\u2705\u270a-\u270b\u2728\u274c\u274e"
    "\u2753-\u2755\u2757\u2795-\u2797\u27b0\u27bf\u2b1b-\u2b1c\u2b50\u2b55\u3030\u303d\ufe0f]"
)
GUARD_TEXT_DIRS = ["docs", "web", ".github"]
GUARD_TEXT_FILES = ["README.md", ".env.example", "Dockerfile"]
GUARD_TEXT_SUFFIXES = {".html", ".js", ".css", ".py", ".md", ".sh", ".bat", ".ps1", ".yml", ".yaml", ".json", ".toml", ".txt", ".example"}
GUARD_SKIP_DIRS = {"__pycache__", ".git"}

TOOL_OPTIONAL_STEPS = {"clang-format", "clang-tidy"}

ENV_KEY_RE = re.compile(r"^([A-Za-z0-9_]+)=")
ENV_NAME_RE = re.compile(r'_env_(?:int|float|positive_float|float_opt|str|list|on|off|first)\(\s*"([A-Za-z0-9_]+)"')
CREDENTIAL_BLOCK_RE = re.compile(r"CREDENTIAL_ENV_NAMES = \(([^)]*)\)", re.DOTALL)
CONFIG_SOURCE = ROOT / "danyapi" / "config.py"
ENV_EXAMPLE = ROOT / ".env.example"
EXTRA_CONFIG_NAMES = frozenset({"DANYAPI_GIGACHAT_CA_FILE"})
ENV_ALIASES = {
    "DANYAPI_GIGACHAT_SCOPE": "GIGACHAT_SCOPE",
    "BYOK": "BYOK_MODE",
    "BYOK_MODE": "BYOK_MODE",
    "DANYAPI_BYOK_MODE": "BYOK_MODE",
}

GREEN = "\033[32m"
YELLOW = "\033[33m"
RED = "\033[31m"
RESET = "\033[0m"

STEP_TIMEOUT_SECONDS = 1200.0

STATUS_PASS = "PASS"
STATUS_FAIL = "FAIL"
STATUS_SKIP = "SKIP"

StepRunner: TypeAlias = list[str] | Callable[[], tuple[bool, str]]
StepResult: TypeAlias = tuple[str, str, float, str, str]


def paint(text: str, color: str, enabled: bool) -> str:
    return f"{color}{text}{RESET}" if enabled else text


def status_paint(status: str, use_color: bool) -> str:
    if status == STATUS_PASS:
        return paint(STATUS_PASS, GREEN, use_color)
    if status == STATUS_SKIP:
        return paint(STATUS_SKIP, YELLOW, use_color)
    return paint(STATUS_FAIL, RED, use_color)


def parse_args(argv: list[str]) -> tuple[int, list[str]]:
    jobs = 1
    pytest_args: list[str] = []
    i = 0
    while i < len(argv):
        arg = argv[i]
        if arg in ("-j", "--jobs"):
            if i + 1 >= len(argv):
                print(f"tests: {arg} requires a value", file=sys.stderr)
                raise SystemExit(2)
            try:
                jobs = int(argv[i + 1])
            except ValueError:
                print(
                    f"tests: {arg} expects an integer, got {argv[i + 1]!r}",
                    file=sys.stderr,
                )
                raise SystemExit(2) from None
            i += 2
            continue
        if arg.startswith("--jobs="):
            value = arg.split("=", 1)[1]
            try:
                jobs = int(value)
            except ValueError:
                print(f"tests: --jobs expects an integer, got {value!r}", file=sys.stderr)
                raise SystemExit(2) from None
            i += 1
            continue
        if arg.startswith("-j") and len(arg) > 2:
            value = arg[2:]
            try:
                jobs = int(value)
            except ValueError:
                print(f"tests: -j expects an integer, got {value!r}", file=sys.stderr)
                raise SystemExit(2) from None
            i += 1
            continue
        pytest_args.append(arg)
        i += 1
    if jobs < 1:
        print(f"tests: job count must be at least 1, got {jobs}", file=sys.stderr)
        raise SystemExit(2)
    return jobs, pytest_args


def iter_guard_targets() -> list[Path]:
    targets = [ROOT / f for f in GUARD_TEXT_FILES]
    for d in GUARD_TEXT_DIRS:
        base = ROOT / d
        if not base.is_dir():
            continue
        targets.extend(p for p in base.rglob("*") if p.is_file() and p.suffix.lower() in GUARD_TEXT_SUFFIXES and not (GUARD_SKIP_DIRS & set(p.parts)))
    return sorted(targets)


def config_env_names() -> set[str]:
    try:
        source = CONFIG_SOURCE.read_text(encoding="utf-8")
    except OSError as exc:
        raise RuntimeError(f"cannot read {CONFIG_SOURCE}: {exc}") from exc
    names = set(ENV_NAME_RE.findall(source))
    block = CREDENTIAL_BLOCK_RE.search(source)
    if block is not None:
        names |= set(re.findall(r'"([A-Za-z0-9_]+)"', block.group(1)))
    return names | set(EXTRA_CONFIG_NAMES)


def env_example_keys() -> list[str]:
    try:
        text = ENV_EXAMPLE.read_text(encoding="utf-8")
    except OSError as exc:
        raise RuntimeError(f"cannot read {ENV_EXAMPLE}: {exc}") from exc
    return [match.group(1) for line in text.splitlines() if (match := ENV_KEY_RE.match(line))]


def check_dashboard_csp() -> list[str]:
    path = ROOT / "web" / "index.html"
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        return [f"{path}: cannot read ({exc})"]
    problems: list[str] = []
    scripts = re.findall(r"<script>(.*?)</script>", text, re.DOTALL)
    if not scripts:
        return [f"{path}: no inline script found, the dashboard hash guard has nothing to check"]
    meta = re.search(r"script-src ([^;\"]+)", text)
    if meta is None:
        return [f"{path}: no script-src in the Content-Security-Policy meta tag"]
    if "'unsafe-inline'" in meta.group(1):
        problems.append(f"{path}: script-src allows 'unsafe-inline', the dashboard hash is not enforced")
    declared = set(re.findall(r"'sha256-([^']+)'", meta.group(1)))
    for script in scripts:
        digest = base64.b64encode(hashlib.sha256(script.encode("utf-8")).digest()).decode()
        if digest not in declared:
            problems.append(f"{path}: script-src does not declare sha256-{digest} for the inline script")
    return problems


def check_env_keys_documented() -> list[str]:
    problems: list[str] = []
    read = config_env_names()
    example = env_example_keys()
    present = set(example)
    for key in sorted(read):
        if key in present:
            continue
        alias = ENV_ALIASES.get(key)
        if alias and alias in present:
            continue
        problems.append(f".env.example: {key} is read by danyapi/config.py but not listed")
    for key in example:
        if key in read:
            continue
        alias = next((name for name, target in ENV_ALIASES.items() if target == key and name in read), None)
        if alias is not None:
            continue
        problems.append(f".env.example: {key} is listed but danyapi/config.py never reads it")
    try:
        readme = (ROOT / "README.md").read_text(encoding="utf-8")
    except OSError as exc:
        return [*problems, f"README.md: cannot read ({exc})"]
    for key in example:
        if key not in readme:
            problems.append(f"README.md: {key} from .env.example is not documented")
    return problems


def check_repo_guards() -> tuple[bool, str]:
    problems: list[str] = []
    for path in iter_guard_targets():
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError as exc:
            problems.append(f"{path}: not utf-8 ({exc})")
            continue
        except OSError as exc:
            problems.append(f"{path}: cannot read ({exc})")
            continue
        for pattern in BANNED_PATTERNS:
            for lineno, line in enumerate(text.splitlines(), 1):
                if pattern in line:
                    problems.append(f"{path}:{lineno}: banned pattern {pattern!r}")
        for lineno, line in enumerate(text.splitlines(), 1):
            lowered = line.lower()
            for needle, label in BANNED_SUBSTRINGS:
                if needle in lowered:
                    problems.append(f"{path}:{lineno}: {label} {needle!r}")
            found = EMOJI_RE.search(line)
            if found is not None:
                problems.append(f"{path}:{lineno}: emoji U+{ord(found.group()):04X}")
    try:
        problems.extend(check_env_keys_documented())
    except RuntimeError as exc:
        problems.append(str(exc))
    problems.extend(check_dashboard_csp())
    if tomllib is None:
        problems.append("pyproject.toml: not validated, no TOML parser available, install tomli or use Python 3.11+")
    else:
        try:
            tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
        except Exception as exc:
            problems.append(f"pyproject.toml: invalid TOML ({exc})")
    for path in ROOT.rglob("*.json"):
        if ".git" in path.parts or "__pycache__" in path.parts:
            continue
        try:
            json.loads(path.read_text(encoding="utf-8"))
        except Exception as exc:
            problems.append(f"{path}: invalid JSON ({exc})")
    if yaml is None:
        problems.append(".github/workflows: not validated, PyYAML is not installed")
    else:
        for path in (ROOT / ".github").rglob("*.yml"):
            try:
                yaml.safe_load(path.read_text(encoding="utf-8"))
            except Exception as exc:
                problems.append(f"{path}: invalid YAML ({exc})")
    if not problems:
        return True, ""
    shown = problems[:40]
    if len(problems) > 40:
        shown.append(f"... and {len(problems) - 40} more")
    return False, f"{len(problems)} problem(s):\n" + "\n".join(shown)


def run_step(name: str, runner: StepRunner, timeout: float = STEP_TIMEOUT_SECONDS) -> StepResult:
    started = time.monotonic()
    if isinstance(runner, list):
        cmd = runner
        detail = " ".join(cmd)
        if cmd[0] != sys.executable and name in TOOL_OPTIONAL_STEPS and shutil.which(cmd[0]) is None:
            elapsed = time.monotonic() - started
            return name, STATUS_SKIP, elapsed, f"tool not found: {cmd[0]}, step skipped", detail
        try:
            proc = subprocess.run(
                cmd,
                cwd=ROOT,
                capture_output=True,
                text=True,
                encoding="utf-8",
                errors="replace",
                check=False,
                timeout=timeout,
            )
        except (FileNotFoundError, NotADirectoryError, PermissionError) as exc:
            elapsed = time.monotonic() - started
            return name, STATUS_FAIL, elapsed, f"tool not runnable: {cmd[0]} ({exc})", detail
        except subprocess.TimeoutExpired:
            elapsed = time.monotonic() - started
            return (
                name,
                STATUS_FAIL,
                elapsed,
                f"timed out after {timeout:.0f}s: {cmd[0]}",
                detail,
            )
        elapsed = time.monotonic() - started
        ok = proc.returncode == 0
        parts: list[str] = []
        if proc.stdout:
            parts.append(proc.stdout.rstrip())
        if proc.stderr:
            parts.append(proc.stderr.rstrip())
        return name, (STATUS_PASS if ok else STATUS_FAIL), elapsed, "\n".join(parts), detail
    try:
        ok, output = runner()
    except Exception as exc:
        elapsed = time.monotonic() - started
        return name, STATUS_FAIL, elapsed, f"step raised {type(exc).__name__}: {exc}", ""
    elapsed = time.monotonic() - started
    return name, (STATUS_PASS if ok else STATUS_FAIL), elapsed, output, ""


def print_step(result: StepResult, use_color: bool, lock: threading.Lock | None = None) -> None:
    name, status, elapsed, output, detail = result
    lines = ["", f"=== [{name}] {detail}".rstrip()]
    if output:
        lines.append(output)
    lines.append(f"=== [{name}] {status_paint(status, use_color)} ({elapsed:.1f}s)")
    text = "\n".join(lines)
    if lock is None:
        print(text)
        return
    with lock:
        print(text)


def build_steps(pytest_args: list[str]) -> list[tuple[str, StepRunner]]:
    return [
        ("repo guards", check_repo_guards),
        ("py_compile", [sys.executable, "-m", "compileall", "-q", "-f", *PYTHON_TARGETS]),
        ("ruff check", [sys.executable, "-m", "ruff", "check", "."]),
        (
            "ruff format --check",
            [sys.executable, "-m", "ruff", "format", "--check", "."],
        ),
        ("isort --check", [sys.executable, "-m", "isort", "--check-only", "."]),
        ("flake8", [sys.executable, "-m", "flake8"]),
        ("pyflakes", [sys.executable, "-m", "pyflakes", *PYTHON_TARGETS]),
        ("mypy", [sys.executable, "-m", "mypy", *PYTHON_TARGETS]),
        (
            "pyright",
            [sys.executable, "-m", "pyright", "--pythonpath", sys.executable, *PYTHON_TARGETS],
        ),
        (
            "pylint",
            [
                sys.executable,
                "-m",
                "pylint",
                "--errors-only",
                "--recursive=y",
                f"--disable={PYLINT_DISABLES}",
                *PYTHON_TARGETS,
            ],
        ),
        (
            "bandit",
            [sys.executable, "-m", "bandit", "-q", "-r", "danyapi", "-s", BANDIT_SKIPS, "-c", "bandit.toml"],
        ),
        (
            "bandit root scripts",
            [sys.executable, "-m", "bandit", "-q", *ROOT_SCRIPTS, "-s", ROOT_BANDIT_SKIPS, "-c", "bandit.toml"],
        ),
        ("vulture", [sys.executable, "-m", "vulture"]),
        ("clang-format", ["clang-format", "--dry-run", *C_SOURCES]),
        (
            "clang-tidy",
            [
                "clang-tidy",
                f"-checks={CLANG_TIDY_CHECKS}",
                *C_SOURCES,
                "--",
                "-std=c11",
                "-D_CRT_SECURE_NO_WARNINGS",
            ],
        ),
        (
            "xenon",
            [
                sys.executable,
                "-m",
                "xenon",
                "--max-absolute",
                "F",
                "--max-modules",
                "D",
                "--max-average",
                "D",
                "danyapi",
                *ROOT_SCRIPTS,
            ],
        ),
        (
            "pip-audit",
            [
                sys.executable,
                "-m",
                "pip_audit",
                "--progress-spinner",
                "off",
                "--timeout",
                "90",
            ],
        ),
        ("pip check", [sys.executable, "-m", "pip", "check"]),
        (
            "pytest",
            [
                sys.executable,
                "-m",
                "pytest",
                "-q",
                "--cov=danyapi",
                "--cov-report=term-missing",
                *pytest_args,
            ],
        ),
    ]


def main() -> int:
    for stream in (sys.stdout, sys.stderr):
        reconfigure = getattr(stream, "reconfigure", None)
        if reconfigure is not None:
            try:
                reconfigure(errors="replace")
            except (ValueError, OSError):
                pass
    jobs, pytest_args = parse_args(sys.argv[1:])
    steps = build_steps(pytest_args)
    use_color = sys.stdout.isatty()
    run_started = time.monotonic()
    results: list[StepResult] = []
    if jobs == 1:
        for name, runner in steps:
            result = run_step(name, runner)
            results.append(result)
            print_step(result, use_color)
    else:
        lock = threading.Lock()
        collected: dict[int, StepResult] = {}
        with ThreadPoolExecutor(max_workers=jobs) as pool:
            futures = {pool.submit(run_step, name, runner): index for index, (name, runner) in enumerate(steps)}
            for future in as_completed(futures):
                result = future.result()
                collected[futures[future]] = result
                print_step(result, use_color, lock)
        results = [collected[index] for index in range(len(steps))]
    wall_time = time.monotonic() - run_started
    print()
    print("======== SUMMARY ========")
    width = max(len(name) for name, *_rest in results)
    failed = 0
    skipped = 0
    for name, status, _elapsed, _output, _detail in results:
        if status == STATUS_PASS:
            mark = status_paint(STATUS_PASS.ljust(4), use_color)
        elif status == STATUS_SKIP:
            skipped += 1
            mark = status_paint(STATUS_SKIP.ljust(4), use_color)
        else:
            failed += 1
            mark = status_paint(STATUS_FAIL.ljust(4), use_color)
        print(f"{mark}  {name.ljust(width)}")
    print()
    if skipped:
        print(f"{skipped} step(s) were skipped because the tool is not installed, see the SKIP lines above.")
    if failed:
        print(f"RESULT: FAILED ({failed} check(s) failed)")
        print(f"total time: {wall_time:.1f}s wall clock across {jobs} job(s)")
        return 1
    print("RESULT: ALL CHECKS PASSED")
    print(f"total time: {wall_time:.1f}s wall clock across {jobs} job(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
